server:
  port: 8080
#  servlet:
#    context-path: /demo
  tomcat:
    accept-count: 150
    max-threads: 500
    uri-encoding: UTF-8
spring:
  application:
    name: demo-two
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
  cache:
    type: redis
  redis:
    database: 1
    host: 192.168.1.41
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 2
    password:
    port: 6379
    timeout: 10s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.41:3306/scm_cms?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      aop-patterns: com.xcky.*
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000
        wall:
          enabled: true
      initial-size: 4
      max-active: 10
      max-open-prepared-statements: 30
      max-wait: 12000
      min-evictable-idle-time-millis: 30000
      min-idle: 4
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        login-password: root
        login-username: root
        reset-enable: false
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
        session-stat-enable: true
        url-pattern: /*
  messages:
    basename: message/messages_zh_CN
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  file:
    max-history: 10
    max-size: 20MB
    name: ./log/${spring.application.name}/${spring.application.name}.log
  level:
    com:
      example:
        demo: debug
  pattern:
    console: '%d - %msg%n'
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.example.entity
pagehelper:
  helper-dialect: mysql
  page-size-zero: true
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
##``````````````````````````````````` tkMapper 配置``````````````````````````````````````````````````````````````###

mapper:
  mappers: com.example.demo.boot.core.TKMapper
